// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxeSsGS8xCX4dveZKRPUDz_0PzxLd_ms',
    appId: '1:358417017610:web:56d96e8c556dece56be8f3',
    messagingSenderId: '358417017610',
    projectId: 'sezel-c1354',
    authDomain: 'sezel-c1354.firebaseapp.com',
    storageBucket: 'sezel-c1354.firebasestorage.app',
    measurementId: 'G-RQ4S9WF1SX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNlP2JcjcMBf5FwDe4tFKzRoIofKOB_o',
    appId: '1:358417017610:ios:4af45bef9cae44016be8f3',
    messagingSenderId: '358417017610',
    projectId: 'sezel-c1354',
    storageBucket: 'sezel-c1354.firebasestorage.app',
    iosBundleId: 'com.sezelhelp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxeSsGS8xCX4dveZKRPUDz_0PzxLd_ms',
    appId: '1:358417017610:web:a65afe41636a73776be8f3',
    messagingSenderId: '358417017610',
    projectId: 'sezel-c1354',
    authDomain: 'sezel-c1354.firebaseapp.com',
    storageBucket: 'sezel-c1354.firebasestorage.app',
    measurementId: 'G-BS14Y66C8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtdyccDVR-OvrV8UF_2dahqR39RnGIIY',
    appId: '1:358417017610:android:515f0a36b332cce86be8f3',
    messagingSenderId: '358417017610',
    projectId: 'sezel-c1354',
    storageBucket: 'sezel-c1354.firebasestorage.app',
  );

}